language: python
python:
  - "2.7"
install:
  - pip install -r dev_requirements.txt
  - pip install --editable .
script:
  - pep8 --count pyfreelan tests
  - coverage run --source=pyfreelan setup.py nosetests --with-doctest --doctest-extension=rst --tests tests,pyfreelan,doc/source
  - sphinx-build -b doctest -W doc/source doc/build/html
  - sphinx-build -b html -W doc/source doc/build/html
  - coverage report -m --fail-under=100
after_success: coveralls
notifications:
    email:
        on_success: change
        on_failure: always
