language: python
python:
  - "2.7"
install:
  - pip install -r dev_requirements.txt
  - pip install --editable .
script:
  - pep8 --count pyfreelan tests
  - coverage run --source=pyfreelan setup.py nosetests --with-doctest
  - coverage report
after_success: coveralls
notifications:
    email:
        on_success: change
        on_failure: always
